### ISSUE TITLE
mongoose is devDependency?

### ISSUE THREAD

**Issue by kimasendorf** [arkon/MERN-boilerplate#1]
Hi,

your boilerplate looks pretty promising! I just wonder why i.e. mongoose is just a devDependency, wouldn't it be needed to serve the api in production too?

=)

**Comment by arkon** [comment]
Whoops, you're right. I've moved mongoose and express to dependencies.

**Comment by kimasendorf** [comment]
nice! thanks for putting it together =)

**Comment by kimasendorf** [comment]
Just tested the dependencies. There is a lot more to move.

```
  "dependencies": {
    "autoprefixer": "^6.6.1",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-class-properties": "^6.22.0",
    "babel-polyfill": "^6.22.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "body-parser": "^1.16.0",
    "connect-history-api-fallback": "^1.3.0",
    "css-loader": "^0.26.1",
    "express": "^4.14.0",
    "extract-text-webpack-plugin": "^2.0.0-beta.5",
    "html-webpack-plugin": "^2.26.0",
    "mongoose": "^4.7.7",
    "nodemon": "^1.11.0",
    "node-sass": "^4.3.0",
    "postcss-loader": "^1.2.2",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-router": "^3.0.2",
    "sass-loader": "^4.1.1",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.0",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.15.0",
    "webpack-merge": "^2.4.0",
    "whatwg-fetch": "^2.0.2"
  },
  "devDependencies": {
    "copy-webpack-plugin": "^4.0.1",
    "react-hot-loader": "^3.0.0-beta.6"
  }
```

**Comment by arkon** [comment]
How exactly are you defining the difference between dependencies and dev dependencies? I typically just put anything build-related in dev (i.e. all that babel and webpack stuff).

**Comment by kimasendorf** [comment]
How and where do you deploy the apps?
When I deploy to a node.js server, all packages needed to make the app running on there, needs to be in the dependencies. Only stuff that isn't needed to make an initial deployment goes to devDependencies.

When you do
```
npm install --production
```
you can basically 'simulate' a production environment. (Delete the node_module folder first)
When you then start your app like you describe in your README
```
npm run start:prod
```
you'll find a lot of missing packages.

**Comment by arkon** [comment]
I guess it depends on how you want to deploy it -- either entirely install dependencies + build on the server, or build first then push.

I personally haven't actually deployed this anywhere, so I never ran into the issue, but I'm welcome to PRs.

**Comment by kimasendorf** [comment]
I am certainly not an expert, but I like your boilerplate because I want to have a single page app along with the express server to serve the data.

**Comment by kimasendorf** [comment]
I'll double check that, but usually I like to deploy my app to be build online, instead of building before deployment.

**Comment by arkon** [comment]
I'm certainly not an expert either, so if it actually makes more sense to move everything, then I'm certainly open to that change. :)

**Comment by kimasendorf** [comment]
Most projects I've seen have mostly just packages for testing and linting in the dev dependencies.

**Comment by arkon** [comment]
Alright, well I just moved all of them to `dependencies`, and I also flipped the scripts so `start` is for prod and `start:dev` is for dev.
