### ISSUE TITLE
How can I make the <head> section different for different pages because of SEO? 

### ISSUE THREAD

**Issue by saeedhei** [arkon/MERN-boilerplate#11]
How can I make the <head> section different for different pages because of SEO? 
**Head of page A:**
`<meta name="robots" content="noindex, nofollow">`
**Head of Page B:**
`<meta name="robots" content="index, follow">`

**Comment by arkon** [comment]
There's plenty of resources online, but maybe [react-meta-tags](https://www.npmjs.com/package/react-meta-tags) fits your needs.

**Comment by saeedhei** [comment]
@arkon Someone said use `helmet js` , is that okey?

**Comment by arkon** [comment]
Isn't that for HTTP headers?

**Comment by saeedhei** [comment]
I Mean this module: (https://github.com/nfl/react-helmet)

**Comment by arkon** [comment]
I don't have any particular advice for this, but that looks like it'd work.
