### ISSUE TITLE
Update webpack-cli to make app run again

### ISSUE THREAD

**Issue by jordan-barber** [arkon/MERN-boilerplate#15]
webpack-cli needs updating to latest in order to get this working again. See https://github.com/webpack/webpack-cli/issues/607 along with below error output: 

```
..../node_modules/webpack-cli/bin/config-yargs.js:91
  describe: optionsSchema.definitions.output.properties.path.description,
				           ^

TypeError: Cannot read property 'properties' of undefined
```

Would be good to get this back working :) See PR https://github.com/arkon/MERN-boilerplate/pull/14

**Comment by arkon** [comment]
Thanks!
