### ISSUE TITLE
cannot deploy to heroku

### ISSUE THREAD

**Issue by sw-yx** [arkon/MERN-boilerplate#2]
i had problems deploying this to heroku. <https://plsdelete19287192871.herokuapp.com/> when in production mode, webpack does not inject the <script> tag into the generated index.html file. i cant figure out how to make it do that.

**Comment by arkon** [comment]
Are you sure webpack ran successfully? `npm start` should already be building in production mode, and it seems to work fine on my end (just tried with a fresh pull, and also updated the repo with some dependency updates just now).

**Comment by sw-yx** [comment]
thanks for the very fast response. i think it ran successfully as there were no error messages in the heroku logs. just to be clear this thing runs fine locally, but it does not work when trying to deploy to heroku. that link above is literally the client/index.html file so i suspected the problem might be this line: <https://github.com/arkon/MERN-boilerplate/blob/master/server/server.js#L55> (basically on heroku when you hit the '/' path it delivers the static file `index.html` from `client` instead of the built `index.html` from `dist`

**Comment by arkon** [comment]
Yeah, you're probably right. It should be pointing to the `dist` folder instead of `client`.

**Comment by Tzikas** [comment]
Did anyone solve this issue? 
I'm having the same problem.

**Comment by krothenbaum** [comment]
This was a push in the right direction but between lines 53 and 57 it should be '../dist' instead of '../dist/public' as there is no public directory in the dist directory.

**Comment by Tzikas** [comment]
+1 krothenbaum

**Comment by arkon** [comment]
@krothenbaum A PR would be welcome. :)

**Comment by arkon** [comment]
Closed via #3.
