### ISSUE TITLE
Not able to connect MongoDB

### ISSUE THREAD

**Issue by vksantoshsunny** [arkon/MERN-boilerplate#5]
I am getting the below error when trying to run. I am using MongoDB cloud version and applied the credentials to the config.js file as given in the instructions

(node:4960) DeprecationWarning: `openSet()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
>>> 🌎 Open http://0.0.0.0:8080/ in your browser.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

**Comment by arkon** [comment]
Should be fixed now.
