### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by rahulb88** [arkon/MERN-boilerplate#7]
After cloning the repo I used npm install for the dependencies and when I run command
> npm run start:dev

getting error 

> MERN-boilerplate@1.0.0 start:dev C:\Users\Rahul Bhardwaj\Documents\test\MERN-boilerplate
> node server

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Rahul Bhardwaj\Documents\test\MERN-boilerplate\"C:\Users\Rahul'    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

**Comment by arkon** [comment]
What version of node are you using?

**Comment by rahulb88** [comment]
I am using node v8.9.3

**Comment by arkon** [comment]
Not really sure. Try deleting `node_modules` and installing them again?
